### ISSUE TITLE
Update readme and contributing

### ISSUE THREAD

**Issue by Shamash2014** [hexlet-volunteers/interviews#81]
I suppose readme must reflect how awesome our app is, what it's primary purpose and how someone can work with it. I think we need update our README. 

Also contributing is our workflow, and for now it's too raw. Consider updating this one too to reflect the whole process, so newcomers will start to build awesome feature right and fast.

**Comment by sashashakun** [comment]
Absolutely agree, I will make some draft in day or two👌

**Comment by sashashakun** [comment]
Cool😐
![2016-03-23 21 33 32](https://cloud.githubusercontent.com/assets/5776864/13996456/e96063b8-f13e-11e5-818e-87e320c29940.png)

**Comment by sashashakun** [comment]
## Contributing Guide

When you want to contribute, at first you should [add an issue](https://github.com/hexlet-volunteers/interviews/issues/new) or take one of the [existing](https://github.com/hexlet-volunteers/interviews/issues). After that you need to take you own copy of project (make sure that you have installed [Ansible](https://www.ansible.com/) and [Vagrant](https://www.vagrantup.com/) on your machine):

1. Get your own fork of the project:
![2016-03-23 22 10 36](https://cloud.githubusercontent.com/assets/5776864/13997644/1cdc10a2-f144-11e5-9241-918e4194df1c.png)

2. Clone it on your machine
```git clone https://github.com/YOUR_USER_NAME/interviews.git && cd interviews```

3. Create virtual machine:
```vagrant up```

4. Connect to it and cd to working dir:
```vagrant ssh```
```cd /vagrant```

5. Install deps
```make install```

6. Create new branch for your awesome feature and checkout
```git checkout -b YOUR_BRANCH_NAME```

7. Working on some feature/bugfix;

8. Push it on github
```git push```

9. Open Pull Request
%need some pic here%


If something is unclear, confusing, or needs to be refactored, please let me know.
Pull requests are always welcome, but due to the opinionated nature of this
project, I cannot accept every pull request. Please open an issue before
submitting a pull request. This project uses
[Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript) with a
few minor exceptions.

**Comment by sashashakun** [comment]
# [Interviews MVP](http://hexlet-interviews.herokuapp.com/)

Первая версия проекта по проведению онлайн собеседований

[![Code Climate](https://codeclimate.com/github/hexlet-volunteers/interviews/badges/gpa.svg)](https://codeclimate.com/github/hexlet-volunteers/interviews)
[![Test Coverage](https://codeclimate.com/github/hexlet-volunteers/interviews/badges/coverage.svg)](https://codeclimate.com/github/hexlet-volunteers/interviews/coverage)
[![Issue Count](https://codeclimate.com/github/hexlet-volunteers/interviews/badges/issue_count.svg)](https://codeclimate.com/github/hexlet-volunteers/interviews)
[![Build Status](https://travis-ci.org/hexlet-volunteers/interviews.svg?branch=master)](https://travis-ci.org/hexlet-volunteers/interviews)


## What is this?

Small app for collect data from people, who want to take part in programming job interview as interviewer or applicant.

## What for?

Besides the above, this is something like testing app, where contibutors can practice their web development skills, work with db, backend, frontend, deploy, and other.

## Want to contribute?

Great! It's easy, read our [contribution guide](CONTRIBUTING.md)
